on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [7, 8, 11, 13, 14]
    steps:
    - uses: actions/checkout@v2
    - run: echo Output for actions/checkout:
    - run: java -version
    - uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}  
    - run: echo Output for actions/setup-java:
    - run: java -version
 
