on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 8.0.144, 15]
    steps:
    - uses: actions/checkout@v2
    - run: java -version
    - uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}  
    - run: java -version
    - name: Build with Ant
      run: ant -noinput -Dbootstrap.url=http://deadlock.netbeans.org/hudson/job/nbms-and-javadoc/lastStableBuild/artifact/nbbuild/netbeans/harness/tasks.jar -Dautoupdate.catalog.url=http://updates.netbeans.org/netbeans/updates/8.0/uc/final/distribution/catalog.xml.gz -buildfile build.xml
    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
